In [2]:
import numpy as np
import sys

# Basics

In [32]:
a = np.array([[1, 3, 5], [1, 3, 4]], dtype='int32')

In [33]:
# Get dimension
a.ndim

2

In [34]:
# Get shape
a.shape

(2, 3)

In [35]:
# Get type
a.dtype

dtype('int32')

In [36]:
# Get size of single item (in bytes)
a.itemsize

4

In [37]:
# Get total size of array (in bytes)
a.nbytes

24

In [39]:
# Get number of items
a.size

6

## Accesing/Changing specific elements, rows, columns, etc.

In [41]:
a = np.arange(1, 8)
b = np.arange(8 ,15)

In [42]:
a, b

(array([1, 2, 3, 4, 5, 6, 7]), array([ 8,  9, 10, 11, 12, 13, 14]))

In [45]:
c = np.stack((a, b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [47]:
# Get a specific element
c[1, 2]

10

In [48]:
# Get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
# Get a specific column
c[:, 3]

array([ 4, 11])

In [53]:
# Getting with step [start:end:step]
c[:, 1:6:2]

array([[ 2,  4,  6],
       [ 9, 11, 13]])

In [54]:
c[0, 0] = 0
c

array([[ 0,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [60]:
c[1, 5:] = [1, 2]
c

array([[ 0,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  5,  1,  2]])

## Initializing different types of arrays

In [63]:
# All 0s matrix
np.zeros(4), np.zeros((3, 2))

(array([0., 0., 0., 0.]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

In [65]:
# All other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [66]:
# Any other number (full_like)
np.full_like(c, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [68]:
# Random decimal numbers [0, 1)
np.random.rand(2, 4, 2)

array([[[0.50366049, 0.10053568],
        [0.62957366, 0.12785052],
        [0.19809876, 0.92403805],
        [0.92113218, 0.99364559]],

       [[0.59020738, 0.69103292],
        [0.92233405, 0.53299288],
        [0.80915555, 0.2016391 ],
        [0.4289979 , 0.22191323]]])

In [77]:
# Random integer values
t = np.random.randint(2, 4, (2, 3))
t, t.dtype

(array([[3, 2, 2],
        [2, 3, 2]]),
 dtype('int64'))

In [80]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
# Repeat an array
t = np.array([[1, 2, 3], [4, 5, 6]])
r1 = np.repeat(t, 3)
r2 = np.repeat(t, 3, axis=0)
t, r1, r2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6]),
 array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]]))

In [93]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:4, 1:4] = z
z[0, 0] = 777
output

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Mathematics

In [108]:
a =np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [109]:
a + 2

array([3, 4, 5, 6])

In [110]:
a - 2

array([-1,  0,  1,  2])

In [111]:
a * 2

array([2, 4, 6, 8])

In [112]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [113]:
a ** 2

array([ 1,  4,  9, 16])

In [116]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Linear algebra

In [119]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)
a, b

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[2, 2],
        [2, 2],
        [2, 2]]))

In [127]:
c = np.matmul(a, b)

In [128]:
np.linalg.det(c)

0.0

### Statistics

In [134]:
stats = np.array([[7, 2, 3], [4, 5, 6]])
stats

array([[7, 2, 3],
       [4, 5, 6]])

In [135]:
np.min(stats)

2

In [137]:
np.max(stats, axis = 1)

array([7, 6])

In [139]:
np.sum(stats), np.sum(stats, axis=0), np.sum(stats, axis=1)

(27, array([11,  7,  9]), array([12, 15]))

## Reorganizing arrays

In [186]:
before = np.array([[1, 2, 3, 4], [4, 3, 2, 1]])

In [187]:
np.random.uniform(2, 2.00000001, (2, 3))

array([[2.        , 2.00000001, 2.00000001],
       [2.        , 2.        , 2.00000001]])

In [193]:
t = np.array([[5 ,6 ,7, 8], [5, 6, 7, 9]])
t

array([[5, 6, 7, 8],
       [5, 6, 7, 9]])

In [195]:
np.append(before,t, axis=0)

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [5, 6, 7, 8],
       [5, 6, 7, 9]])

In [ ]:
np.array()